# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtb" do
  name "gtb"
  desc "A helper utility for interacting and managing gtb repos and resources"
  homepage "https://github.com/phpboyscout/go-tool-base"
  version "1.7.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtb"
  depends_on formula: [
      "go",
      "golangci-lint",
    ]

  on_macos do
    on_intel do
      url "https://github.com//phpboyscout/go-tool-base/releases/download/v#{version}/gtb_Darwin_x86_64.tar.gz"
      sha256 "0120f1f71e416249d56706c5c3b3eed81f6fc0b2e63fb28c0da07af71a9e13f3"
    end
    on_arm do
      url "https://github.com//phpboyscout/go-tool-base/releases/download/v#{version}/gtb_Darwin_arm64.tar.gz"
      sha256 "0465ae310cd87408b6316758ccd208c394a3df9caff3d84703dd1ee82b6debcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com//phpboyscout/go-tool-base/releases/download/v#{version}/gtb_Linux_x86_64.tar.gz"
      sha256 "13de1dea99dcaa32289516c8722c3355ee756d311f8d87a59b3052eb8c45d2af"
    end
    on_arm do
      url "https://github.com//phpboyscout/go-tool-base/releases/download/v#{version}/gtb_Linux_arm64.tar.gz"
      sha256 "6ef3f57d856c4f82c0b9368f62e8a4ad332acfd6e09c2bbffe29a0b7856441a7"
    end
  end

  # No zap stanza required
end
