# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtb" do
  name "gtb"
  desc "A helper utility for interacting and managing gtb repos and resources"
  homepage "https://github.com/phpboyscout/gtb"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtb"
  depends_on formula: [
      "go",
      "golangci-lint",
    ]

  on_macos do
    on_intel do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Darwin_x86_64.tar.gz"
      sha256 "3f125958f9cd882ff1bf24c568c6eca032fd7e577e3224ceefb685a861598351"
    end
    on_arm do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Darwin_arm64.tar.gz"
      sha256 "2813522733b956567ab35549f1daf4e4c4a44acd9a6fb12659b32b7ed99ed423"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Linux_x86_64.tar.gz"
      sha256 "8139e0cd227c16cd1c492619b6b9c94fba29de8ced38a0b377dfa18e9045d4fc"
    end
    on_arm do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Linux_arm64.tar.gz"
      sha256 "8da4d52c13f6eb88943254103bb2646715c5c5ab667b9b8163b0aee6fc8d0ef6"
    end
  end

  # No zap stanza required
end
