# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtb" do
  name "gtb"
  desc "A helper utility for interacting and managing gtb repos and resources"
  homepage "https://github.com/phpboyscout/gtb"
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtb"
  depends_on formula: [
      "go",
      "golangci-lint",
    ]

  on_macos do
    on_intel do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Darwin_x86_64.tar.gz"
      sha256 "55a1f53497e131981d737fa6326b15c43fdf6f89cf3791757343133aa35adf18"
    end
    on_arm do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Darwin_arm64.tar.gz"
      sha256 "6151a9a4394381cc2a062225a5194e1dc0a062b9c9de338165ba925c01cb5314"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Linux_x86_64.tar.gz"
      sha256 "f201e2356d0953ffb385bac23aca881bff000df456e9d78642de2920aa1d4fa5"
    end
    on_arm do
      url "https://github.com//phpboyscout/gtb/releases/download/v#{version}/gtb_Linux_arm64.tar.gz"
      sha256 "6009b6f7365b083b167d9e0dedb11b97d7d82b0c969de2ce9b603b2a60bc3f21"
    end
  end

  # No zap stanza required
end
